tasks:
  - name: Install Mamba
    init: |
      curl -fsSL https://micro.mamba.pm/install.sh | bash
      echo 'export PATH="$HOME/micromamba/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      
 
