tasks:
  - name: Install Conda & Mamba and BUSCO
    init: |
      # Install Miniconda and Mamba
      wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc

      # Initialize Mamba and update it
      conda update -n base -c defaults conda -y
      conda install -n base -c conda-forge mamba -y
      mamba shell init --shell bash --root-prefix=~/.local/share/mamba
      eval "$(mamba shell hook --shell bash)"

      # Install BUSCO in a new environment using Mamba
      mamba create -n ONT25 -y bioconda::busco

      # Activate the ONT25 environment in the same terminal
      echo "mamba activate ONT25" >> ~/.bashrc
      source ~/.bashrc
