tasks:
  - name: Install Conda
    init: |
      wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      conda update -n base -c defaults conda -y
      conda install -n base -c conda-forge mamba -y
      
